### ISSUE TITLE
exception in phase 'canonicalization' in source unit ... errors

### ISSUE THREAD

**Issue by vspinu** [GroovyLanguageServer/groovy-language-server#36]
I am using groovy-language-server with emacs and lsp-mode with `javac 11.0.9.1`. I am seeing the following error

```
BUG! exception in phase 'canonicalization' in source unit '/home/vspinu/.../xyz.groovy' ClassNode#getTypeClass for groovy_scripts_utils.utils.test_util.ApplicantModifierTest is called before the type class is set 
	at org.codehaus.groovy.ast.ClassNode.getTypeClass(ClassNode.java:1387)
	at org.codehaus.groovy.ast.ClassNode.getTypeClass(ClassNode.java:1381)
	at org.codehaus.groovy.transform.trait.Traits.findHelpers(Traits.java:149)
	at org.codehaus.groovy.transform.trait.TraitComposer.doExtendTraits(TraitComposer.java:110)
	at org.codehaus.groovy.control.CompilationUnit$5.call(CompilationUnit.java:235)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1084)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:640)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:618)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:595)
	at net.prominic.groovyls.GroovyServices.compile(GroovyServices.java:448)
	at net.prominic.groovyls.GroovyServices.compileAndVisitAST(GroovyServices.java:431)
	at net.prominic.groovyls.GroovyServices.didOpen(GroovyServices.java:138)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Unexpected exception in language server when compiling Groovy.
```

The project is rather big and I am not a groovy programmer. I see rather long delays and frequent hangs. I presume it has to do with this error.

**Comment by joshtynjala** [comment]
Do you think that you can try to strip it down to a small class or single file? It looks like the error is happening around this code: `groovy_scripts_utils.utils.test_util.ApplicantModifierTest`, but there's not much I can suggest beyond that.

**Comment by vspinu** [comment]
I will try to isolate tomorrow, but my expertize is pretty limited. Unfortunately it's a private repo.

**Comment by aminroosta** [comment]
I have the same issue in https://github.com/dansomething/coc-groovy/issues/20 which uses this repository.

This [has been fixed](https://github.com/apache/groovy/pull/524) in newer groovy versions, but I'm stuck on grails 3 and can't really upgrade 😢
